spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kmpc
    username: kmpc
    password: kmpc
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

logging:
  level:
    root: info