jwt:
  header: Authorization
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

upload:
  path: C:/temp_/file/
  path2: /Users/taehyunkwon/temp/

cloud:
  aws:
    s3:
      bucket: kmpc-img-bucket
    credentials:
      access-key: AKIA5GWRXYVSPUV7R4W6
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB
  #  datasource:
#    driver-class-name: org.postgresql.Driver
#    url: jdbc:postgresql://localhost:5432/kmpc
#    username: kmpc
#    password: kmpc
  datasource:
    url: jdbc:mysql://ec2-13-125-207-204.ap-northeast-2.compute.amazonaws.com:3306/kmpc?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    cache: false
    check-template-location: true
    prefix: file:src/main/resources/templates/
    suffix: .html
    enabled: true

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    restart:
      enabled: true

  freemarker:
    cache: false

  # cache:
  #   type: redis
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379

  data:
    web:
      pageable:
        default-page-size: 16
  web:
    resources:
      static-locations: file:src/main/resources/static/
logging:
  level:
    root: info
    org.hibernate.sql: debug