# Default
spring:
  profiles:
    active: dev
---
# prod
jwt:
  header: Authorization
  domain: ec2-13-125-207-204.ap-northeast-2.compute.amazonaws.com
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

upload:
  path: C:/temp_/file/
  path2: /home/ubuntu

cloud:
  aws:
    s3:
      bucket: kmpc-img-bucket
    credentials:
      access-key: AKIA5GWRXYVSPUV7R4W6
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

spring:

  config:
    activate:
      on-profile: prod

  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

  datasource:
    url: jdbc:mysql://ec2-13-125-207-204.ap-northeast-2.compute.amazonaws.com:3306/kmpc?serverTimezone=UTC&characterEncoding=UTF-8&useUnicode=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  thymeleaf:
    #    cache: false
    check-template-location: true
    suffix: .html
    enabled: true

  # cache:
  #   type: redis
  # data:
  #   redis:
  #     host: localhost
  #     port: 6379

  data:
    web:
      pageable:
        default-page-size: 16
#  web:
#    resources:
#      static-locations: classPath:/src/main/resources/static/
logging:
  level:
    root: info
    org.hibernate.sql: debug

---
# dev
spring:

  config:
    activate:
      on-profile: dev

  mvc:
    hiddenmethod:
      filter:
        enabled: true

  servlet:
    multipart:
      max-file-size: 11MB
      max-request-size: 11MB

  devtools:
    remote:
      restart:
        enabled: true
    livereload:
      enabled: true
    restart:
      enabled: true


  datasource:
    url: jdbc:mysql://ec2-13-125-207-204.ap-northeast-2.compute.amazonaws.com:3306/kmpc?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true


  freemarker:
    cache: false

  data:
    web:
      pageable:
        default-page-size: 16
  #  web:
  #    resources:
  #      static-locations: classPath:/src/main/resources/static/
  logging:
    level:
      root: info
      org.hibernate.sql: debug


jwt:
  header: Authorization
  domain: localhost
  #HS512 알고리즘을 사용할 것이기 때문에 512bit, 즉 64byte 이상의 secret key를 사용해야 한다.
  #echo 'silvernine-tech-spring-boot-jwt-tutorial-secret-silvernine-tech-spring-boot-jwt-tutorial-secret'|base64
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400

upload:
  path: C:/temp_/file/
  path2: /home/ubuntu

cloud:
  aws:
    s3:
      bucket: kmpc-img-bucket
    credentials:
      access-key: AKIA5GWRXYVSPUV7R4W6
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    root: debug
    org.hibernate.sql: debug
